version: "3"

services:
  classification-service:
      build:
        context: .
        dockerfile: Dockerfile-dev
      image: wccs/classification-service:dev
      ports:
        - "44284:44284"
        - "9229:9229"
      volumes:
        - ./:/usr/src/app:ro
        - ./resources/classification-model.json:/conf/classification-model.json:ro